# Generated by Django 6.0.6 on 2026-08-26 17:58

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_remove_loginhistory_organizatio_user_id_f5b768_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('Feature Film', 'Feature Film'), ('Episodic Series', 'Episodic Series'), ('Commercial', 'Commercial'), ('Game Cinematic', 'Game Cinematic')], db_index=True, default='Feature Film', max_length=30)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Archived', 'Archived'), ('On Hold', 'On Hold')], db_index=True, default='In Progress', max_length=30)),
                ('fps', models.DecimalField(decimal_places=3, default=24, max_digits=5)),
                ('resolution', models.CharField(blank=True, default='4096x2160 (4K DCI)', max_length=50)),
                ('aspect_ratio', models.CharField(blank=True, default='2.39:1', max_length=20)),
                ('color_space', models.CharField(blank=True, default='ACEScg', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('total_shots', models.PositiveIntegerField(default=0)),
                ('approved_shots', models.PositiveIntegerField(default=0)),
                ('in_progress_shots', models.PositiveIntegerField(default=0)),
                ('total_assets', models.PositiveIntegerField(default=0)),
                ('budget_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client_id', models.CharField(blank=True, default='', max_length=50)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('client_contact_id', models.CharField(blank=True, default='', max_length=50)),
                ('client_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_ids', models.JSONField(blank=True, default=list)),
                ('vendor_names', models.JSONField(blank=True, default=list)),
                ('vendor_team_ids', models.JSONField(blank=True, default=list)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organization.organization')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_project',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('Character', 'Character'), ('Environment', 'Environment'), ('Vehicle', 'Vehicle'), ('Prop', 'Prop'), ('FX Rig', 'FX Rig'), ('Shader & LookDev', 'Shader & LookDev'), ('Matte Painting', 'Matte Painting'), ('Crowd Agent', 'Crowd Agent'), ('Costume / Groom', 'Costume / Groom')], db_index=True, default='Prop', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Retake', 'Retake'), ('Archived', 'Archived')], db_index=True, default='Not Started', max_length=30)),
                ('version', models.CharField(blank=True, default='v001', max_length=20)),
                ('file_format', models.CharField(blank=True, default='OpenUSD (.usda)', max_length=100)),
                ('poly_count', models.PositiveIntegerField(default=0)),
                ('lod_levels', models.PositiveIntegerField(default=1)),
                ('software', models.CharField(blank=True, choices=[('Maya', 'Maya'), ('Houdini', 'Houdini'), ('Blender', 'Blender'), ('ZBrush', 'ZBrush'), ('Substance Painter', 'Substance Painter'), ('Unreal Engine 5', 'Unreal Engine 5'), ('Solaris', 'Solaris'), ('Mari', 'Mari')], default='Maya', max_length=30)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('turntable_video_url', models.URLField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('usd_prim_path', models.CharField(blank=True, default='', max_length=255)),
                ('usd_stage_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('versions', models.JSONField(blank=True, default=list)),
                ('hierarchy', models.JSONField(blank=True, default=list)),
                ('assigned_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organization.organization')),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='production.asset')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.team')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='production.project')),
            ],
            options={
                'db_table': 'production_asset',
                'ordering': ('code',),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('sequence_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Retake', 'Retake'), ('On Hold', 'On Hold')], db_index=True, default='Not Started', max_length=30)),
                ('frame_in', models.IntegerField(default=1001)),
                ('frame_out', models.IntegerField(default=1100)),
                ('handle_frames', models.PositiveIntegerField(default=8)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('current_version', models.CharField(blank=True, default='v001', max_length=20)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('client_approved', models.BooleanField(default=False)),
                ('pipeline', models.JSONField(blank=True, default=dict, help_text='Pipeline stage statuses')),
                ('assigned_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shots', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='organization.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='production.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_shot',
                'ordering': ('code',),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'code'], name='production__organiz_004878_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='production__organiz_044807_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'type'], name='production__organiz_b7f712_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'project'], name='production__organiz_4d58b7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'category'], name='production__project_7c3f30_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='production__status_8d2eec_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_archived'], name='production__is_arch_c9f60d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['organization', 'project'], name='production__organiz_eb47e5_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['project', 'sequence_code'], name='production__project_4b506a_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['project', 'code'], name='production__project_85b55c_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['status'], name='production__status_1b987f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together={('project', 'code')},
        ),
    ]
