# Generated by Django 6.0.6 on 2026-08-26 18:08

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_loginhistory_organizatio_user_id_f5b768_idx_and_more'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, default='Shot', help_text='Shot, Asset, Sequence, General', max_length=20)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('entity_code', models.CharField(blank=True, default='', max_length=50)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('department_id', models.CharField(blank=True, default='', max_length=50)),
                ('vendor_id', models.CharField(blank=True, default='', max_length=50)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=50)),
                ('workflow', models.JSONField(blank=True, default=dict)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('dependencies', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('software', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Retake', 'Retake'), ('Archived', 'Archived')], db_index=True, default='Not Started', max_length=30)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Medium', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('logged_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organization.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organization.team')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_task',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='Timelog',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('task_code', models.CharField(blank=True, default='', max_length=50)),
                ('task_title', models.CharField(blank=True, default='', max_length=255)),
                ('project_code', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(db_index=True)),
                ('billable', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Submitted', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('activity_category', models.CharField(blank=True, default='Direct Work', max_length=50)),
                ('hourly_rate_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timelogs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='organization.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='production.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='production.task')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_timelog',
                'ordering': ('-date', '-created_at'),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'project'], name='production__organiz_fd11fe_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'entity_type'], name='production__project_a67afe_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'entity_id'], name='production__project_3a588d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='production__status_1db029_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='production__priorit_f39393_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_archived'], name='production__is_arch_ea5a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department'], name='production__departm_dd6e6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['organization', 'project'], name='production__organiz_93a9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['task'], name='production__task_id_e9510d_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['person'], name='production__person__da1169_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['status'], name='production__status_2b2319_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['billable'], name='production__billabl_ee9d48_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['date'], name='production__date_2ccad6_idx'),
        ),
    ]
