# Generated by Django 6.0.6 on 2026-08-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_media_playlist_review_version_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_format',
            field=models.CharField(blank=True, default='jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, db_index=True, default='image', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='storage_tier',
            field=models.CharField(blank=True, default='hot', max_length=50),
        ),
    ]
