# Generated by Django 6.0.6 on 2026-09-01 18:00

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_currency_and_more'),
        ('production', '0004_alter_media_file_format_alter_media_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Retake', 'Retake'), ('Archived', 'Archived')], db_index=True, default='Not Started', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('frame_in', models.PositiveIntegerField(default=1001)),
                ('frame_out', models.PositiveIntegerField(default=1100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='organization.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='production.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_sequence',
                'ordering': ('code',),
                'indexes': [models.Index(fields=['organization', 'project'], name='production__organiz_fdacd1_idx'), models.Index(fields=['project', 'code'], name='production__project_fd1f70_idx'), models.Index(fields=['status'], name='production__status_c91c0f_idx')],
                'unique_together': {('project', 'code')},
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
