# Generated by Django 6.0.6 on 2026-09-07 11:08

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0013_organization_billing"),
        ("production", "0005_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialCut",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence_code",
                    models.CharField(blank=True, db_index=True, default="", max_length=50),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(db_index=True, max_length=50)),
                (
                    "cut_type",
                    models.CharField(
                        choices=[
                            ("Conform", "Conform"),
                            ("Turnover", "Turnover"),
                            ("Rough Cut", "Rough Cut"),
                            ("Fine Cut", "Fine Cut"),
                            ("Picture Lock", "Picture Lock"),
                            ("Trailer Teaser", "Trailer Teaser"),
                        ],
                        db_index=True,
                        default="Turnover",
                        max_length=30,
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=20)),
                ("fps", models.FloatField(default=24)),
                ("duration_frames", models.PositiveIntegerField(default=0)),
                ("duration_tc", models.CharField(blank=True, default="", max_length=20)),
                ("start_tc", models.CharField(blank=True, default="", max_length=20)),
                ("end_tc", models.CharField(blank=True, default="", max_length=20)),
                ("source_edl_filename", models.CharField(blank=True, default="", max_length=255)),
                ("xml_manifest_url", models.URLField(blank=True, default="", max_length=500)),
                ("total_shots_in_cut", models.PositiveIntegerField(default=0)),
                ("matched_vfx_shots", models.PositiveIntegerField(default=0)),
                ("unmatched_shots", models.PositiveIntegerField(default=0)),
                ("editorial_notes", models.TextField(blank=True, default="")),
                ("editor_name", models.CharField(blank=True, default="", max_length=255)),
                ("conformed_by", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Pending Review", "Pending Review"),
                            ("Approved", "Approved"),
                            ("Retake", "Retake"),
                            ("Archived", "Archived"),
                        ],
                        db_index=True,
                        default="Not Started",
                        max_length=30,
                    ),
                ),
                ("burn_in_lut", models.CharField(blank=True, default="", max_length=255)),
                ("thumbnail_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_cuts",
                        to="organization.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_cuts",
                        to="production.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "production_editorial_cut",
                "ordering": ("code",),
                "indexes": [
                    models.Index(
                        fields=["organization", "project"], name="production__organiz_d7daeb_idx"
                    ),
                    models.Index(fields=["project", "code"], name="production__project_36f36f_idx"),
                    models.Index(fields=["status"], name="production__status_3a0686_idx"),
                ],
                "unique_together": {("project", "code")},
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(db_index=True, default="Artist", max_length=100)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("scope", models.CharField(db_index=True, default="PROJECT", max_length=30)),
                ("status", models.CharField(db_index=True, default="Active", max_length=20)),
                ("department", models.CharField(blank=True, default="", max_length=100)),
                ("department_id", models.CharField(blank=True, default="", max_length=50)),
                ("team_id", models.CharField(blank=True, default="", max_length=50)),
                ("vendor_id", models.CharField(blank=True, default="", max_length=50)),
                ("client_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="organization.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="production.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "production_project_membership",
                "ordering": ("project", "user"),
                "indexes": [
                    models.Index(
                        fields=["organization", "project"], name="production__organiz_f7f997_idx"
                    ),
                    models.Index(
                        fields=["project", "status"], name="production__project_90f8b1_idx"
                    ),
                    models.Index(fields=["user", "status"], name="production__user_id_2b9fd7_idx"),
                ],
                "unique_together": {("project", "user")},
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, default="Project", max_length=20)),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=50),
                ),
                ("entity_code", models.CharField(blank=True, default="", max_length=50)),
                ("entity_name", models.CharField(blank=True, default="", max_length=255)),
                ("author_name", models.CharField(blank=True, default="", max_length=255)),
                ("author_avatar", models.URLField(blank=True, default="", max_length=500)),
                ("author_role", models.CharField(blank=True, default="", max_length=100)),
                ("subject", models.CharField(db_index=True, max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Director Feedback", "Director Feedback"),
                            ("Supervisor Note", "Supervisor Note"),
                            ("Client Note", "Client Note"),
                            ("Pipeline Notice", "Pipeline Notice"),
                            ("Turnover Requirement", "Turnover Requirement"),
                            ("General", "General"),
                        ],
                        db_index=True,
                        default="General",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        db_index=True,
                        default="Medium",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Addressed", "Addressed"),
                            ("Closed", "Closed"),
                        ],
                        db_index=True,
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("addressed_by", models.CharField(blank=True, default="", max_length=255)),
                ("addressed_at", models.DateTimeField(blank=True, null=True)),
                ("timecode_ref", models.CharField(blank=True, default="", max_length=20)),
                ("frame_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_notes",
                        to="organization.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="production.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "production_project_note",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "project"], name="production__organiz_a4685a_idx"
                    ),
                    models.Index(
                        fields=["project", "status"], name="production__project_15f34e_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="production__entity__add3e5_idx"
                    ),
                ],
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
