# Generated by Django 6.0.6 on 2026-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_editorialcut_projectmembership_projectnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shot",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("Pending Review", "Pending Review"),
                    ("Approved", "Approved"),
                    ("Retake", "Retake"),
                    ("On Hold", "On Hold"),
                    ("Archived", "Archived"),
                ],
                db_index=True,
                default="Not Started",
                max_length=30,
            ),
        ),
    ]
