# Generated by Django 6.0.6 on 2026-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_media_code_media_file_name_media_name_media_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
