# Generated by Django 6.0.6 on 2026-09-16 07:08

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0016_person_organization_and_more"),
        ("production", "0010_automationrule_automationauditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialTrack",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cut_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("cut_name", models.CharField(blank=True, default="", max_length=255)),
                ("track_number", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "track_type",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("Audio", "Audio"),
                            ("VFX Plates", "VFX Plates"),
                            ("Reference", "Reference"),
                            ("Subtitles", "Subtitles"),
                            ("Markers", "Markers"),
                        ],
                        db_index=True,
                        default="Video",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("codec_or_format", models.CharField(blank=True, default="", max_length=255)),
                (
                    "channels_or_resolution",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("frame_rate", models.FloatField(default=24)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_solo", models.BooleanField(default=False)),
                ("color_tag", models.CharField(blank=True, default="", max_length=20)),
                ("clip_count", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Conformed", "Conformed"),
                            ("Muted", "Muted"),
                            ("Archived", "Archived"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=30,
                    ),
                ),
                ("start_tc", models.CharField(blank=True, default="", max_length=20)),
                ("end_tc", models.CharField(blank=True, default="", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_tracks",
                        to="organization.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_tracks",
                        to="production.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "production_editorial_track",
                "ordering": ("project", "track_number"),
                "indexes": [
                    models.Index(
                        fields=["organization", "project"], name="production__organiz_ebf705_idx"
                    ),
                    models.Index(
                        fields=["project", "track_number"], name="production__project_175421_idx"
                    ),
                    models.Index(fields=["status"], name="production__status_7ff526_idx"),
                ],
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
