# Generated by Django 6.0.6 on 2026-09-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0012_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="show",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional show binding (ADR-0033 D2): narrows this membership to a single show within the project.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="production.show",
            ),
        ),
    ]
