# Generated by Django 6.0.6 on 2026-09-30 08:07

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0019_normalize_organization_status"),
        ("production", "0013_projectmembership_show"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("season_number", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Pending Review", "Pending Review"),
                            ("Approved", "Approved"),
                            ("Retake", "Retake"),
                            ("Archived", "Archived"),
                        ],
                        db_index=True,
                        default="Not Started",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("frame_in", models.PositiveIntegerField(default=1001)),
                ("frame_out", models.PositiveIntegerField(default=1100)),
                ("duration_frames", models.PositiveIntegerField(blank=True, null=True)),
                ("air_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="organization.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="production.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "production_episode",
                "ordering": ("season_number", "episode_number", "code"),
                "indexes": [
                    models.Index(
                        fields=["organization", "project"], name="production__organiz_554c69_idx"
                    ),
                    models.Index(fields=["project", "code"], name="production__project_fa3631_idx"),
                    models.Index(
                        fields=["project", "season_number", "episode_number"],
                        name="production__project_41d250_idx",
                    ),
                    models.Index(fields=["status"], name="production__status_80772c_idx"),
                ],
                "unique_together": {("project", "code")},
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
