# Generated by Django 6.0.6 on 2026-09-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0014_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workflow_type",
            field=models.CharField(
                choices=[("standard", "Standard"), ("episodic", "Episodic")],
                db_index=True,
                default="standard",
                help_text="'episodic' projects bootstrap an initial episode on create and allow episode creation; 'standard' projects have no episodes.",
                max_length=20,
            ),
        ),
    ]
