# Generated by Django 6.0.6 on 2026-09-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0015_project_workflow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shot",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shots",
                to="production.episode",
            ),
        ),
    ]
