# Generated by Django 6.0.6 on 2026-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0016_shot_episode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On Leave"),
                    ("terminated", "Terminated"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
