# Generated by Django 6.0.6 on 2026-10-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0036_backfill_person_user"),
        ("production", "0018_map_project_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="role_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical RBAC role (N7 consolidation). `role` Char stays as display snapshot.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_memberships",
                to="organization.role",
            ),
        ),
    ]
