# Generated by Django 4.2.30 on 2026-08-27 09:27

import apps.core.models.mixins.soft_delete
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_alter_organization_currency_and_more'),
        ('production', '0004_alter_media_file_format_alter_media_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name', max_length=100)),
                ('rule_type', models.CharField(choices=[('file_exists', 'File Exists'), ('file_size', 'File Size'), ('frame_range', 'Frame Range'), ('file_format', 'File Format'), ('metadata', 'Metadata'), ('dependencies', 'Dependencies'), ('permissions', 'Permissions')], help_text='Type of validation rule', max_length=50)),
                ('action', models.CharField(choices=[('warn', 'Warn'), ('error', 'Error'), ('block', 'Block')], default='error', help_text='Action to take on failure', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Rule configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for rule execution')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this rule was created')),
            ],
            options={
                'verbose_name': 'Publish Validation Rule',
                'verbose_name_plural': 'Publish Validation Rules',
                'db_table': 'publishing_validation_rule',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PublishItem',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Publish item name', max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Publish code', max_length=50)),
                ('entity_type', models.CharField(choices=[('Shot', 'Shot'), ('Asset', 'Asset')], db_index=True, help_text='Entity type being published', max_length=20)),
                ('entity_id', models.CharField(db_index=True, help_text='ID of the entity being published', max_length=100)),
                ('entity_code', models.CharField(help_text='Code of the entity being published', max_length=255)),
                ('entity_name', models.CharField(help_text='Name of the entity being published', max_length=255)),
                ('dcc_tool', models.CharField(choices=[('Maya', 'Maya'), ('Houdini', 'Houdini'), ('Blender', 'Blender'), ('Nuke', 'Nuke'), ('Maya Light', 'Maya Light'), ('Cinema 4D', 'Cinema 4D'), ('3ds Max', '3ds Max')], help_text='DCC tool used for publish', max_length=20)),
                ('dcc_version', models.CharField(blank=True, help_text='DCC tool version', max_length=50)),
                ('source_file', models.CharField(help_text='Source file path', max_length=500)),
                ('source_version', models.CharField(blank=True, help_text='Source file version', max_length=50)),
                ('export_path', models.CharField(blank=True, help_text='Exported file path', max_length=500)),
                ('export_format', models.CharField(blank=True, help_text='Export format (USD, FBX, Alembic, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validating', 'Validating'), ('Validated', 'Validated'), ('Exporting', 'Exporting'), ('Exported', 'Exported'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', help_text='Publish status', max_length=20)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules applied')),
                ('validation_results', models.JSONField(blank=True, default=dict, help_text='Validation results')),
                ('export_options', models.JSONField(blank=True, default=dict, help_text='Export options')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this publish is archived')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization context', on_delete=django.db.models.deletion.CASCADE, related_name='publish_items', to='organization.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Associated project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_items', to='production.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publish Item',
                'verbose_name_plural': 'Publish Items',
                'db_table': 'publishing_item',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
