# Generated by Django 6.0.6 on 2026-09-05 12:32

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_alter_organization_currency_and_more"),
        ("publishing", "0002_publishvalidationrule_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishDestination",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=255)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("Storage Cluster", "Storage Cluster"),
                            ("Client Delivery Ingest", "Client Delivery Ingest"),
                            ("Render Farm Cache", "Render Farm Cache"),
                            ("Cloud S3 Bucket", "Cloud S3 Bucket"),
                            ("Vendor Ingest", "Vendor Ingest"),
                            ("Daily Review Repo", "Daily Review Repo"),
                            ("USD Asset Cache", "USD Asset Cache"),
                        ],
                        db_index=True,
                        help_text="Destination type",
                        max_length=30,
                    ),
                ),
                ("path", models.CharField(help_text="Storage path or URI", max_length=500)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("NFS", "NFS"),
                            ("SMB", "SMB"),
                            ("S3", "S3"),
                            ("Aspera", "Aspera"),
                            ("Local POSIX", "Local POSIX"),
                        ],
                        help_text="Transfer protocol",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default destination for new publishes"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="Region or location description", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this destination is available"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_destinations",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publish Destination",
                "verbose_name_plural": "Publish Destinations",
                "db_table": "publishing_destination",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"),
                        name="uniq_publish_destination_name_per_org",
                    )
                ],
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
