# Generated by Django 6.0.6 on 2026-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0003_publishdestination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishitem",
            name="dcc_tool",
            field=models.CharField(
                choices=[
                    ("Maya", "Maya"),
                    ("Houdini", "Houdini"),
                    ("Blender", "Blender"),
                    ("Nuke", "Nuke"),
                    ("Maya Light", "Maya Light"),
                    ("Cinema 4D", "Cinema 4D"),
                    ("3ds Max", "3ds Max"),
                    ("Unreal", "Unreal"),
                    ("USD", "USD"),
                ],
                help_text="DCC tool used for publish",
                max_length=20,
            ),
        ),
    ]
