# Generated by Django 4.2.30 on 2026-08-27 09:27

import apps.core.models.mixins.soft_delete
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_alter_organization_currency_and_more'),
        ('production', '0004_alter_media_file_format_alter_media_media_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPackage',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Delivery package name', max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Unique delivery code', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Validating', 'Validating'), ('Prepared', 'Prepared'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', help_text='Delivery package status', max_length=20)),
                ('client_status', models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', help_text='Client-facing status', max_length=20)),
                ('delivery_method', models.CharField(choices=[('Aspera', 'Aspera'), ('S3', 'S3'), ('FTP', 'FTP'), ('Web Download', 'Web Download')], default='S3', help_text='Delivery method', max_length=20)),
                ('delivery_destination', models.TextField(blank=True, help_text='Delivery destination (URL, path, etc.)')),
                ('passcode', models.CharField(blank=True, help_text='Security passcode for client access', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When this delivery expires', null=True)),
                ('total_size_bytes', models.PositiveBigIntegerField(default=0, help_text='Total size of all versions in bytes')),
                ('total_frames', models.PositiveIntegerField(default=0, help_text='Total frames across all versions')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this delivery')),
                ('client_notes', models.TextField(blank=True, help_text='Notes visible to client')),
                ('manifest_data', models.JSONField(blank=True, default=dict, help_text='Delivery manifest data (EDL, XML, etc.)')),
                ('checksums', models.JSONField(blank=True, default=dict, help_text='File checksums (MD5, SHA256)')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this delivery is archived')),
                ('client', models.ForeignKey(blank=True, help_text='Client recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_packages', to='organization.client')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization context', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_packages', to='organization.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Associated project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_packages', to='production.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Package',
                'verbose_name_plural': 'Delivery Packages',
                'db_table': 'deliveries_package',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='DeliveryVersionRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Version number at time of delivery', max_length=50)),
                ('entity_type', models.CharField(help_text='Entity type (Shot, Asset)', max_length=50)),
                ('entity_code', models.CharField(help_text='Entity code', max_length=255)),
                ('entity_name', models.CharField(help_text='Entity display name', max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('frame_count', models.PositiveIntegerField(default=0, help_text='Number of frames')),
                ('file_path', models.CharField(help_text='File path or URL', max_length=500)),
                ('checksum_md5', models.CharField(blank=True, help_text='MD5 checksum', max_length=32)),
                ('checksum_sha256', models.CharField(blank=True, help_text='SHA256 checksum', max_length=64)),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this version has passed QC validation')),
                ('validation_notes', models.TextField(blank=True, help_text='QC validation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this reference was added')),
                ('delivery', models.ForeignKey(help_text='Delivery package', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='deliveries.deliverypackage')),
                ('version', models.ForeignKey(help_text='Version being delivered', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_references', to='production.version')),
            ],
            options={
                'verbose_name': 'Delivery Version Reference',
                'verbose_name_plural': 'Delivery Version References',
                'db_table': 'deliveries_version_ref',
                'ordering': ('version_number',),
                'unique_together': {('delivery', 'version')},
            },
        ),
    ]
