# Generated by Django 6.0.6 on 2026-09-05 12:32

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
        ("organization", "0009_alter_organization_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDestination",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=255)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("Aspera Connect", "Aspera Connect"),
                            ("Signiant Media Shuttle", "Signiant Media Shuttle"),
                            ("AWS S3 Bucket", "AWS S3 Bucket"),
                            ("Frame.io Enterprise", "Frame.io Enterprise"),
                            ("LTO Tape Archive", "LTO Tape Archive"),
                            ("Client SFTP", "Client SFTP"),
                            ("Hard Drive Ingest", "Hard Drive Ingest"),
                        ],
                        db_index=True,
                        help_text="Destination type",
                        max_length=30,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="Endpoint address, URL, or bucket", max_length=500),
                ),
                (
                    "credentials_configured",
                    models.BooleanField(
                        default=False, help_text="Whether transfer credentials are configured"
                    ),
                ),
                (
                    "transfer_rate_mbps",
                    models.PositiveIntegerField(
                        blank=True, help_text="Expected transfer rate in Mbps", null=True
                    ),
                ),
                (
                    "storage_region",
                    models.CharField(
                        blank=True, help_text="Storage region description", max_length=255
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, help_text="Connection port, if applicable", null=True
                    ),
                ),
                (
                    "target_directory",
                    models.CharField(
                        blank=True, help_text="Target directory on the remote end", max_length=500
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default destination for new deliveries"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this destination is available"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_destinations",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Destination",
                "verbose_name_plural": "Delivery Destinations",
                "db_table": "deliveries_destination",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"),
                        name="uniq_delivery_destination_name_per_org",
                    )
                ],
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
