import { FieldDefinition } from '@/types/crud';

export const SHOT_FIELDS: FieldDefinition[] = [
  { key: 'code', label: 'Shot Code', type: 'text', required: true, width: 140, sortable: true },
  { key: 'name', label: 'Shot Name', type: 'text', required: true, width: 180, sortable: true },
  {
    key: 'status',
    label: 'Status',
    type: 'status',
    required: true,
    width: 130,
    sortable: true,
    options: [
      { label: 'Not Started', value: 'Not Started' },
      { label: 'In Progress', value: 'In Progress' },
      { label: 'Pending Review', value: 'Pending Review' },
      { label: 'Approved', value: 'Approved' },
      { label: 'Completed', value: 'Completed' },
      { label: 'Omitted', value: 'Omitted' },
    ],
  },
  {
    key: 'project_id',
    label: 'Project',
    type: 'reference',
    referenceType: 'project',
    required: true,
    width: 150,
  },
  {
    key: 'assigned_artist_id',
    label: 'Assigned Artist',
    type: 'reference',
    referenceType: 'person',
    width: 160,
  },
  { key: 'frame_count', label: 'Frames', type: 'number', width: 90, sortable: true },
  { key: 'current_version', label: 'Version', type: 'text', width: 100 },
  { key: 'due_date', label: 'Due Date', type: 'date', width: 120, sortable: true },
  { key: 'description', label: 'Description', type: 'text', hiddenByDefault: true },
];

export const TASK_FIELDS: FieldDefinition[] = [
  { key: 'code', label: 'Task Code', type: 'text', required: true, width: 130, sortable: true },
  { key: 'title', label: 'Task Title', type: 'text', required: true, width: 220, sortable: true },
  {
    key: 'status',
    label: 'Status',
    type: 'status',
    required: true,
    width: 130,
    sortable: true,
    options: [
      { label: 'Not Started', value: 'Not Started' },
      { label: 'In Progress', value: 'In Progress' },
      { label: 'Pending Review', value: 'Pending Review' },
      { label: 'Approved', value: 'Approved' },
      { label: 'Completed', value: 'Completed' },
    ],
  },
  {
    key: 'priority',
    label: 'Priority',
    type: 'priority',
    required: true,
    width: 110,
    sortable: true,
    options: [
      { label: 'Low', value: 'Low' },
      { label: 'Medium', value: 'Medium' },
      { label: 'High', value: 'High' },
      { label: 'Urgent', value: 'Urgent' },
    ],
  },
  {
    key: 'department',
    label: 'Department',
    type: 'select',
    required: true,
    width: 130,
    options: [
      { label: 'Compositing', value: 'Compositing' },
      { label: 'Lighting', value: 'Lighting' },
      { label: 'Animation', value: 'Animation' },
      { label: 'Layout', value: 'Layout' },
      { label: 'FX / Dynamics', value: 'FX / Dynamics' },
      { label: 'Matchmove', value: 'Matchmove' },
    ],
  },
  {
    key: 'project_id',
    label: 'Project',
    type: 'reference',
    referenceType: 'project',
    required: true,
    width: 150,
  },
  {
    key: 'assignee_id',
    label: 'Assignee',
    type: 'reference',
    referenceType: 'person',
    width: 160,
  },
  { key: 'due_date', label: 'Due Date', type: 'date', width: 120, sortable: true },
  { key: 'logged_hours', label: 'Hours', type: 'number', width: 90, sortable: true },
  { key: 'description', label: 'Description', type: 'text', hiddenByDefault: true },
];

export const PROJECT_FIELDS: FieldDefinition[] = [
  { key: 'code', label: 'Project Code', type: 'text', required: true, width: 130, sortable: true },
  { key: 'name', label: 'Project Name', type: 'text', required: true, width: 220, sortable: true },
  {
    key: 'status',
    label: 'Status',
    type: 'status',
    required: true,
    width: 130,
    sortable: true,
    options: [
      { label: 'Bidding', value: 'Bidding' },
      { label: 'In Production', value: 'In Production' },
      { label: 'Active', value: 'Active' },
      { label: 'In Review', value: 'In Review' },
      { label: 'Completed', value: 'Completed' },
      { label: 'Archived', value: 'Archived' },
    ],
  },
  {
    key: 'client_id',
    label: 'Client Organization',
    type: 'reference',
    referenceType: 'client',
    required: true,
    width: 180,
  },
  { key: 'progress', label: 'Progress', type: 'progress', width: 130, sortable: true },
  { key: 'delivery_date', label: 'Delivery Date', type: 'date', width: 120, sortable: true },
  { key: 'budget', label: 'Budget ($)', type: 'currency', width: 110, sortable: true },
  { key: 'description', label: 'Description', type: 'text', hiddenByDefault: true },
];
