# Generated by Django 6.0.6 on 2026-08-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="status",
        ),
    ]
