import React, { useState } from 'react';
import {
  FileText,
  Download,
  Calendar,
  Filter,
  Search,
  Plus,
  BarChart2,
  CheckCircle2,
  Clock,
  Sparkles,
  ArrowUpRight,
} from 'lucide-react';
import { useProductionReports } from '@/modules/organization/hooks/useOrganizationData';
import { Button } from '@/shared/components/Button';
import { Badge } from '@/shared/components/Badge';
import { cn } from '@/shared/utils/cn';

export const ReportsPage: React.FC = () => {
  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('ALL');
  const { data: reports, isLoading } = useProductionReports();

  const filtered = (reports || []).filter(
    (r) =>
      (categoryFilter === 'ALL' || r.category === categoryFilter) &&
      (r.title.toLowerCase().includes(search.toLowerCase()) ||
        r.project_code.toLowerCase().includes(search.toLowerCase()))
  );

  return (
    <div className="space-y-5 animate-in fade-in duration-200 max-w-5xl">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pb-4 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-400" />
            <h1 className="text-xl font-bold text-white tracking-tight">Production Reports & Bids Audit</h1>
            <Badge variant="outline" className="font-mono text-xs text-indigo-300 border-indigo-500/30">
              {reports?.length || 0} Executive Audits
            </Badge>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Studio bids vs actuals reconciliation, milestone delivery turnover checklists, and compute blade telemetry.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <div className="relative">
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search reports..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="bg-slate-900 border border-slate-800 rounded-lg pl-8 pr-3 py-1.5 text-xs text-slate-200 placeholder-slate-500 focus:outline-hidden focus:border-indigo-500 w-56"
            />
          </div>

          <Button
            size="sm"
            variant="primary"
            leftIcon={<Plus className="w-3.5 h-3.5" />}
            onClick={() => alert('New Automated Report generation scheduled')}
          >
            Generate Report
          </Button>
        </div>
      </div>

      {/* Category Filter */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1">
        {['ALL', 'Milestone Tracking', 'Bids vs Actuals', 'Farm Utilization'].map((cat) => (
          <button
            key={cat}
            onClick={() => setCategoryFilter(cat)}
            className={cn(
              'px-3 py-1 rounded-lg text-xs font-medium transition-all whitespace-nowrap',
              categoryFilter === cat
                ? 'bg-indigo-600/20 text-indigo-300 border border-indigo-500/40'
                : 'bg-slate-900/60 text-slate-400 hover:text-slate-200 border border-slate-800'
            )}
          >
            {cat === 'ALL' ? 'All Reports' : cat}
          </button>
        ))}
      </div>

      {/* Reports List */}
      <div className="space-y-4">
        {filtered.map((report) => (
          <div
            key={report.id}
            className="p-5 rounded-2xl bg-slate-900 border border-slate-800 hover:border-slate-700 transition-all space-y-4"
          >
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="font-bold text-sm text-white">{report.title}</h3>
                  <span className="px-1.5 py-0.2 rounded bg-indigo-950 font-mono text-[10px] font-bold text-indigo-300 border border-indigo-500/30">
                    {report.project_code}
                  </span>
                  <Badge
                    variant="outline"
                    className="bg-emerald-500/10 text-emerald-400 border-emerald-500/30 text-[10px] font-mono"
                  >
                    {report.status}
                  </Badge>
                </div>
                <span className="text-xs text-slate-400 font-mono mt-1 block">
                  Category: {report.category} • Generated by {report.generated_by} on {report.generated_at}
                </span>
              </div>

              <Button
                size="sm"
                variant="outline"
                leftIcon={<Download className="w-3.5 h-3.5" />}
                onClick={() => alert(`Downloading ${report.title} PDF report...`)}
              >
                Download PDF
              </Button>
            </div>

            {/* Metrics Breakdown Bento */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
              {Object.entries(report.summary_metrics).map(([key, val]) => (
                <div
                  key={key}
                  className="p-2.5 rounded-xl bg-slate-950/70 border border-slate-800/80 space-y-0.5"
                >
                  <span className="text-[10px] font-mono text-slate-400 block truncate">{key}</span>
                  <span className="text-sm font-bold text-white font-mono block">{String(val)}</span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
