# Generated by Django 6.0.6 on 2026-09-16 12:35

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0016_person_organization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionReport",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Report title", max_length=255)),
                (
                    "project_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Project code the report refers to",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, help_text="Report category", max_length=100
                    ),
                ),
                (
                    "generated_at",
                    models.CharField(
                        blank=True, help_text="Human-readable generation timestamp", max_length=100
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        blank=True, help_text="Who generated the report", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Complete", "Complete"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Complete",
                        help_text="Report status",
                        max_length=20,
                    ),
                ),
                (
                    "summary_metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Flexible summary metrics"
                    ),
                ),
                (
                    "download_url",
                    models.CharField(blank=True, help_text="Report download URL", max_length=500),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Report",
                "verbose_name_plural": "Production Reports",
                "db_table": "platform_production_report",
                "ordering": ("-created_at",),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name="StudioNotification",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Notification title", max_length=255)),
                ("message", models.TextField(blank=True, help_text="Notification body")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        help_text="Notification type",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, help_text="Notification category", max_length=100
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="Client-side route link", max_length=500
                    ),
                ),
                (
                    "timestamp",
                    models.CharField(
                        blank=True, help_text="Human-readable timestamp label", max_length=50
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional notification metadata"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Studio Notification",
                "verbose_name_plural": "Studio Notifications",
                "db_table": "platform_studio_notification",
                "ordering": ("-created_at",),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
