from django.urls import include, path

from apps.identity.api.routers import (
    urlpatterns as router_urls,
)
from apps.identity.api.views.authentication import (
    ChangePasswordAPIView,
    ForgotPasswordAPIView,
    LoginAPIView,
    LogoutAPIView,
    RefreshAPIView,
    ResendVerificationAPIView,
    ResetPasswordAPIView,
    VerifyEmailAPIView,
)

from .views.authentication import (
    MFADisableAPIView,
    MFAEnrollAPIView,
    MFARecoveryCodesAPIView,
    MFARecoveryVerifyAPIView,
    MFAVerifyAPIView,
    TrustedDeviceListAPIView,
    TrustedDeviceRevokeAPIView,
)

urlpatterns = [
    path(
        "identity/",
        include(router_urls),
    ),
    path(
        "login/",
        LoginAPIView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutAPIView.as_view(),
        name="logout",
    ),
    path(
        "refresh/",
        RefreshAPIView.as_view(),
        name="refresh",
    ),
    path(
        "password/change/",
        ChangePasswordAPIView.as_view(),
        name="change-password",
    ),
    path(
        "password/forgot/",
        ForgotPasswordAPIView.as_view(),
        name="forgot-password",
    ),
    path(
        "password/reset/",
        ResetPasswordAPIView.as_view(),
        name="reset-password",
    ),
    path(
        "email/verify/",
        VerifyEmailAPIView.as_view(),
        name="verify-email",
    ),
    path(
        "email/resend/",
        ResendVerificationAPIView.as_view(),
        name="resend-verification",
    ),
    path(
        "auth/mfa/enroll/",
        MFAEnrollAPIView.as_view(),
        name="mfa-enroll",
    ),
    path(
        "auth/mfa/verify/",
        MFAVerifyAPIView.as_view(),
        name="mfa-verify",
    ),
    path(
        "auth/mfa/disable/",
        MFADisableAPIView.as_view(),
        name="mfa-disable",
    ),
    path(
        "auth/mfa/recovery/",
        MFARecoveryCodesAPIView.as_view(),
        name="mfa-recovery",
    ),
    path(
        "auth/mfa/recovery/verify/",
        MFARecoveryVerifyAPIView.as_view(),
        name="mfa-recovery-verify",
    ),
    path(
        "auth/mfa/devices/",
        TrustedDeviceListAPIView.as_view(),
        name="trusted-devices",
    ),
    path(
        "auth/mfa/devices/revoke/",
        TrustedDeviceRevokeAPIView.as_view(),
        name="trusted-device-revoke",
    ),
]
