user nginx;

worker_processes auto;

pid /var/run/nginx.pid;

events {
    worker_connections 2048;
    multi_accept on;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    client_max_body_size 20G;

    types_hash_max_size 4096;

    include /etc/nginx/conf.d/*.conf;

    ##
    ## Compression
    ##

    gzip on;
    gzip_vary on;
    gzip_proxied any;

    gzip_comp_level 6;

    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        application/xml+rss
        application/vnd.ms-fontobject
        application/x-font-ttf
        font/opentype
        image/svg+xml;

    ##
    ## Logging
    ##

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

}
