# Generated by Django 6.0.6 on 2026-08-04 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("feature_usage", "Feature Usage"),
                            ("interaction", "Interaction"),
                            ("search", "Search"),
                            ("filter", "Filter"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("report", "Report"),
                            ("dashboard", "Dashboard"),
                            ("notification", "Notification"),
                        ],
                        db_index=True,
                        help_text="Type of activity",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="success",
                        help_text="Status of the activity",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the activity"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration of the activity in seconds", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata about the activity"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="APIRequest",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("OPTIONS", "OPTIONS"),
                            ("HEAD", "HEAD"),
                        ],
                        db_index=True,
                        help_text="HTTP method",
                        max_length=10,
                    ),
                ),
                ("path", models.CharField(db_index=True, help_text="Request path", max_length=500)),
                (
                    "full_path",
                    models.TextField(
                        blank=True, help_text="Full request path with query parameters"
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(db_index=True, help_text="HTTP status code"),
                ),
                (
                    "status_category",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("client_error", "Client Error"),
                            ("server_error", "Server Error"),
                        ],
                        db_index=True,
                        help_text="Status category",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "request_size_bytes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Request size in bytes", null=True
                    ),
                ),
                (
                    "response_size_bytes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Response size in bytes", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the requester", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string")),
                (
                    "api_version",
                    models.CharField(blank=True, help_text="API version", max_length=20),
                ),
                (
                    "request_headers",
                    models.JSONField(blank=True, default=dict, help_text="Request headers"),
                ),
                (
                    "request_body",
                    models.JSONField(blank=True, default=dict, help_text="Request body"),
                ),
                (
                    "response_headers",
                    models.JSONField(blank=True, default=dict, help_text="Response headers"),
                ),
                (
                    "response_body",
                    models.JSONField(blank=True, default=dict, help_text="Response body"),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message (if any)")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_requests",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Request",
                "verbose_name_plural": "API Requests",
                "db_table": "api_requests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("permission_change", "Permission Change"),
                            ("role_change", "Role Change"),
                            ("import", "Import"),
                            ("export", "Export"),
                            ("api_call", "API Call"),
                            ("background_job", "Background Job"),
                            ("error", "Error"),
                            ("track", "Track"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        help_text="Severity level of the event",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("organization", "Organization"),
                            ("team", "Team"),
                            ("match", "Match"),
                            ("tournament", "Tournament"),
                            ("scoring", "Scoring"),
                            ("notification", "Notification"),
                            ("streaming", "Streaming"),
                            ("billing", "Billing"),
                            ("branding", "Branding"),
                            ("analytics", "Analytics"),
                            ("ai", "AI"),
                            ("video", "Video"),
                            ("setting", "Setting"),
                            ("feature_flag", "Feature Flag"),
                            ("theme", "Theme"),
                            ("localization", "Localization"),
                        ],
                        db_index=True,
                        help_text="Type of target affected",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        db_index=True, help_text="ID of the target affected", max_length=100
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True, help_text="Name of the target affected", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description of the event")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata about the event"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("export", "Export"),
                            ("import", "Import"),
                            ("report", "Report"),
                            ("sync", "Sync"),
                            ("cleanup", "Cleanup"),
                            ("notification", "Notification"),
                            ("analytics", "Analytics"),
                            ("backup", "Backup"),
                            ("reindex", "Reindex"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of background job",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("progress", "Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Current status of the job",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description of the job")),
                (
                    "job_id",
                    models.CharField(
                        db_index=True, help_text="Unique job ID", max_length=100, unique=True
                    ),
                ),
                (
                    "queue_name",
                    models.CharField(blank=True, help_text="Name of the queue", max_length=100),
                ),
                (
                    "worker_id",
                    models.CharField(blank=True, help_text="ID of the worker", max_length=100),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="When the job started", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When the job completed", null=True),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, help_text="Job result data"),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message (if any)")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_jobs",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Background Job",
                "verbose_name_plural": "Background Jobs",
                "db_table": "background_jobs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        db_index=True,
                        help_text="Type of change",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        db_index=True, help_text="Type of target affected", max_length=100
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        db_index=True, help_text="ID of the target affected", max_length=100
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True, help_text="Name of the target affected", max_length=255
                    ),
                ),
                (
                    "before_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="Values before the change"
                    ),
                ),
                (
                    "after_values",
                    models.JSONField(blank=True, default=dict, help_text="Values after the change"),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True, default=list, help_text="List of fields that changed"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the change"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Log",
                "verbose_name_plural": "Change Logs",
                "db_table": "change_logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                            ("fatal", "Fatal"),
                        ],
                        db_index=True,
                        default="error",
                        help_text="Severity of the error",
                        max_length=20,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("exception", "Exception"),
                            ("api_error", "API Error"),
                            ("database_error", "Database Error"),
                            ("cache_error", "Cache Error"),
                            ("file_error", "File Error"),
                            ("auth_error", "Auth Error"),
                            ("validation_error", "Validation Error"),
                            ("permission_error", "Permission Error"),
                            ("network_error", "Network Error"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of error",
                        max_length=50,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, help_text="Error code", max_length=100),
                ),
                ("message", models.TextField(help_text="Error message")),
                ("stack_trace", models.TextField(blank=True, help_text="Full stack trace")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address where the error occurred", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string")),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        help_text="Request path where the error occurred",
                        max_length=500,
                    ),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, help_text="HTTP method", max_length=10),
                ),
                (
                    "context_data",
                    models.JSONField(blank=True, default=dict, help_text="Additional context data"),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Whether the error has been resolved"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the error was resolved", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_logs",
                        to="organization.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who resolved the error",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_error_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User affected by the error",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "db_table": "error_logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("mfa_verify", "MFA Verify"),
                            ("device_login", "Device Login"),
                        ],
                        db_index=True,
                        help_text="Type of login event",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="success",
                        help_text="Status of the login event",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the login", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent string")),
                (
                    "location",
                    models.CharField(blank=True, help_text="Location of the login", max_length=255),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(default=False, help_text="Whether MFA was used"),
                ),
                (
                    "mfa_type",
                    models.CharField(blank=True, help_text="Type of MFA used", max_length=50),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, help_text="Session ID", max_length=100),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, help_text="Name of the device", max_length=255),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, help_text="Type of device", max_length=50),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, help_text="Reason for login failure"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_login_history",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who logged in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login History",
                "verbose_name_plural": "Login History",
                "db_table": "login_history",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("click", "Click"),
                            ("form_submit", "Form Submit"),
                            ("search", "Search"),
                            ("filter", "Filter"),
                            ("sort", "Sort"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("download", "Download"),
                            ("upload", "Upload"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        help_text="Type of event",
                        max_length=50,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(blank=True, help_text="Name of the event", max_length=255),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, help_text="Session ID", max_length=100),
                ),
                ("page_url", models.CharField(blank=True, help_text="Page URL", max_length=500)),
                (
                    "page_title",
                    models.CharField(blank=True, help_text="Page title", max_length=255),
                ),
                (
                    "element_id",
                    models.CharField(
                        blank=True, help_text="Element ID (for clicks)", max_length=255
                    ),
                ),
                (
                    "element_text",
                    models.CharField(
                        blank=True, help_text="Element text (for clicks)", max_length=255
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event metadata"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who triggered the event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
                "db_table": "tracks",
                "ordering": ("-created_at",),
            },
        ),
    ]
