# Generated by Django 6.0.6 on 2026-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apirequest",
            name="status",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="status",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="status",
        ),
        migrations.RemoveField(
            model_name="errorlog",
            name="status",
        ),
        migrations.RemoveField(
            model_name="track",
            name="status",
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="browser",
            field=models.CharField(
                blank=True, help_text="Browser used for the login", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="browser_version",
            field=models.CharField(
                blank=True, help_text="Browser version used for the login", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="login_method",
            field=models.CharField(
                blank=True,
                default="password",
                help_text="Authentication method used (password, sso, mfa, api_token, ...)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="operating_system",
            field=models.CharField(
                blank=True, help_text="Operating system used for the login", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("mfa_verify", "MFA Verify"),
                    ("device_login", "Device Login"),
                ],
                db_index=True,
                default="login",
                help_text="Type of login event",
                max_length=50,
            ),
        ),
    ]
