# Generated by Django 6.0.6 on 2026-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_loginhistory_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("organization", "Organization"),
                    ("team", "Team"),
                    ("project", "Project"),
                    ("sequence", "Sequence"),
                    ("shot", "Shot"),
                    ("asset", "Asset"),
                    ("task", "Task"),
                    ("version", "Version"),
                    ("review", "Review"),
                    ("playlist", "Playlist"),
                    ("media", "Media"),
                    ("workflow", "Workflow"),
                    ("delivery", "Delivery"),
                    ("notification", "Notification"),
                    ("billing", "Billing"),
                    ("branding", "Branding"),
                    ("analytics", "Analytics"),
                    ("ai", "AI"),
                    ("video", "Video"),
                    ("setting", "Setting"),
                    ("feature_flag", "Feature Flag"),
                    ("theme", "Theme"),
                    ("localization", "Localization"),
                ],
                db_index=True,
                help_text="Type of target affected",
                max_length=50,
            ),
        ),
    ]
