# Generated by Django 6.0.6 on 2026-08-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="status",
        ),
        migrations.RemoveField(
            model_name="branding",
            name="status",
        ),
        migrations.RemoveField(
            model_name="calendar",
            name="status",
        ),
        migrations.RemoveField(
            model_name="department",
            name="status",
        ),
        migrations.RemoveField(
            model_name="group",
            name="status",
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="status",
        ),
        migrations.RemoveField(
            model_name="grouprole",
            name="status",
        ),
        migrations.RemoveField(
            model_name="holiday",
            name="status",
        ),
        migrations.RemoveField(
            model_name="office",
            name="status",
        ),
        migrations.RemoveField(
            model_name="organizationsettings",
            name="status",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="personalaccesstoken",
            name="status",
        ),
        migrations.RemoveField(
            model_name="position",
            name="status",
        ),
        migrations.RemoveField(
            model_name="role",
            name="status",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="team",
            name="status",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="status",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="status",
        ),
        migrations.RemoveField(
            model_name="workcalendar",
            name="status",
        ),
        migrations.RemoveField(
            model_name="workhours",
            name="status",
        ),
    ]
