# Generated by Django 6.0.6 on 2026-08-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_remove_apikey_status_remove_branding_status_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="organizatio_user_id_f5b768_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="organizatio_status_bf7b3d_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="organizatio_authent_1e2289_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="organizatio_organiz_bc1bb6_idx",
        ),
        migrations.DeleteModel(
            name="LoginHistory",
        ),
    ]
