# Generated by Django 6.0.6 on 2026-08-27 05:45

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_loginhistory_organizatio_user_id_f5b768_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('studio_type', models.CharField(blank=True, default='Major Studio', max_length=50)),
                ('active_projects', models.JSONField(blank=True, default=list)),
                ('contract_tier', models.CharField(blank=True, default='Standard Producer', max_length=50)),
                ('portal_access', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, db_index=True, default='Active', max_length=30)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('headquarters', models.CharField(blank=True, default='', max_length=255)),
                ('total_billed_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_client',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['organization', 'code'], name='organizatio_organiz_552f62_idx'), models.Index(fields=['organization', 'status'], name='organizatio_organiz_073a81_idx')],
                'unique_together': {('organization', 'code')},
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Object creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('specialization', models.CharField(blank=True, default='Roto & Paint', max_length=100)),
                ('security_tier', models.CharField(blank=True, default='Standard Studio NDA', max_length=100)),
                ('nda_signed', models.BooleanField(default=False)),
                ('active_tasks_count', models.PositiveIntegerField(default=0)),
                ('active_projects', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, default='Approved Partner', max_length=30)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('bandwidth_gbps', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='User who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_vendor',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['organization', 'code'], name='organizatio_organiz_e5802a_idx'), models.Index(fields=['organization', 'status'], name='organizatio_organiz_599bab_idx')],
                'unique_together': {('organization', 'code')},
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
