# Generated by Django 6.0.6 on 2026-09-06 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_client_vendor_contracts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="clientcontract",
            constraint=models.UniqueConstraint(
                fields=("organization", "client", "contract_number"),
                name="uq_client_contract_org_client_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcontract",
            constraint=models.UniqueConstraint(
                fields=("organization", "vendor", "contract_number"),
                name="uq_vendor_contract_org_vendor_number",
            ),
        ),
    ]
