# Generated by Django 6.0.6 on 2026-09-06 05:48

import apps.core.models.mixins.soft_delete
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0012_contract_unique_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationBilling",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tier", models.CharField(default="Enterprise Vanguard", max_length=50)),
                ("monthly_base_fee_usd", models.PositiveIntegerField(default=12500)),
                ("farm_credits_total", models.PositiveBigIntegerField(default=500000)),
                ("farm_credits_used", models.PositiveBigIntegerField(default=0)),
                ("storage_quota_tb", models.PositiveIntegerField(default=500)),
                ("storage_used_tb", models.FloatField(default=0)),
                ("active_seats_count", models.PositiveIntegerField(default=0)),
                ("max_seats_count", models.PositiveIntegerField(default=300)),
                ("next_billing_date", models.DateField(blank=True, default=None, null=True)),
                ("invoice_currency", models.CharField(default="USD ($)", max_length=20)),
                ("payment_method", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_billing",
                "ordering": ("organization__code",),
            },
            bases=(models.Model, apps.core.models.mixins.soft_delete.SoftDeleteMixin),
        ),
    ]
