# Generated by Django 6.0.6 on 2026-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0013_organization_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="headquarters",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display location required by the frontend contract.",
                max_length=255,
                verbose_name="Headquarters",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="primary_contact_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Primary Contact Name"
            ),
        ),
    ]
