# Generated by Django 6.0.6 on 2026-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0014_organization_headquarters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
