# Generated by Django 6.0.6 on 2026-09-11 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0015_alter_role_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_persons",
                to="organization.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["organization", "name"], name="organizatio_organiz_02b25f_idx"
            ),
        ),
    ]
