# Generated by Django 6.0.6 on 2026-09-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0017_canonical_permission_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="scope",
            field=models.CharField(
                choices=[
                    ("organization", "Organization"),
                    ("project", "Project"),
                    ("show", "Show"),
                    ("department", "Department"),
                    ("team", "Team"),
                    ("office", "Office"),
                ],
                db_index=True,
                default="organization",
                max_length=30,
            ),
        ),
    ]
