# Generated by Django 6.0.6 on 2026-09-30 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0019_normalize_organization_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons",
                to="organization.position",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="scope",
            field=models.CharField(
                choices=[
                    ("global_master", "Global Master"),
                    ("organization_custom", "Organization Custom"),
                ],
                db_index=True,
                default="organization_custom",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="organization.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", False), ("scope", "organization_custom")),
                    ("scope", "global_master"),
                    _connector="OR",
                ),
                name="position_scope_organization_link",
            ),
        ),
    ]
