"""Adopt drift FK column primary_supervisor on organizations.

Live schema carries ``primary_supervisor_id`` (UUID, nullable, FK to
``organization_person``) with no model counterpart, so the frontend
supervisor selector could neither save nor reload. Adopted with
existing data preserved; no-op where the column already exists.
"""

# Generated by Django 6.0.6 on 2026-10-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0027_headquarters_office_fk"),
    ]

    database_operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE organizations "
                "ADD COLUMN IF NOT EXISTS primary_supervisor_id UUID "
                "REFERENCES organization_person(id) ON DELETE SET NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]

    state_operations = [
        migrations.AddField(
            model_name="organization",
            name="primary_supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Person backing the primary supervisor selector.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_organizations",
                to="organization.person",
                verbose_name="Primary Supervisor",
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
