# Generated by Django 6.0.6 on 2026-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0028_primary_supervisor_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="banner_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External banner image URL shown on the workspace.",
                max_length=500,
                verbose_name="Banner URL",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External logo URL (fallback for the uploaded logo).",
                max_length=500,
                verbose_name="Logo URL",
            ),
        ),
    ]
