# Generated by Django 6.0.6 on 2026-10-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0029_organization_branding_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="capacity_hours_weekly",
            field=models.PositiveIntegerField(default=160),
        ),
        migrations.AddField(
            model_name="department",
            name="color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="department",
            name="software_stack",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="department",
            name="utilization_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="office",
            name="headcount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="office",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="office",
            name="render_nodes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="office",
            name="working_hours",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="office",
            name="workstations_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="person",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons",
                to="organization.department",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons",
                to="organization.office",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="security_clearance",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="seniority",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="person",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="person",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons",
                to="organization.team",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="current_project_code",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="team",
            name="focus_discipline",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="team",
            name="utilization_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="organization.person",
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_offices",
                to="organization.person",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_led_teams",
                to="organization.person",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="bandwidth_link",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
