# Generated by Django 6.0.6 on 2026-10-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0036_backfill_person_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rolepermission",
            table="organization_role_permission",
        ),
    ]
