# Generated by Django 6.0.6 on 2026-08-04 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Localization",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the localization",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Display name for the localization", max_length=255
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("ko", "Korean"),
                            ("ru", "Russian"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        help_text="Default language",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("Asia/Kolkata", "India (IST)"),
                            ("Asia/Dubai", "Dubai (GST)"),
                            ("Europe/London", "London (GMT/BST)"),
                            ("Europe/Paris", "Paris (CET)"),
                            ("America/New_York", "New York (EST/EDT)"),
                            ("America/Los_Angeles", "Los Angeles (PST/PDT)"),
                            ("Australia/Sydney", "Sydney (AEST/AEDT)"),
                        ],
                        default="UTC",
                        help_text="Default timezone",
                        max_length=50,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                            ("DD-MM-YYYY", "DD-MM-YYYY"),
                            ("MM-DD-YYYY", "MM-DD-YYYY"),
                            ("YYYY/MM/DD", "YYYY/MM/DD"),
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                        ],
                        default="YYYY-MM-DD",
                        help_text="Default date format",
                        max_length=30,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("24H", "24 Hour"), ("12H", "12 Hour")],
                        default="24H",
                        help_text="Default time format",
                        max_length=10,
                    ),
                ),
                (
                    "number_format",
                    models.CharField(
                        choices=[("dot", "1,234.56"), ("comma", "1.234,56")],
                        default="dot",
                        help_text="Default number format",
                        max_length=10,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="USD", help_text="Currency code (ISO 4217)", max_length=3
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(default="$", help_text="Currency symbol", max_length=5),
                ),
                (
                    "week_start",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="First day of week (0=Sunday, 1=Monday)"
                    ),
                ),
                (
                    "fiscal_year_start",
                    models.DateField(
                        blank=True, help_text="Start date of fiscal year (MM-DD)", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether this localization is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this localization belongs to (null = default)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localizations",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Localization",
                "verbose_name_plural": "Localizations",
                "db_table": "localizations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SettingCategory",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("match", "Match"),
                            ("tournament", "Tournament"),
                            ("scoring", "Scoring"),
                            ("notification", "Notification"),
                            ("streaming", "Streaming"),
                            ("billing", "Billing"),
                            ("branding", "Branding"),
                            ("analytics", "Analytics"),
                            ("ai", "AI"),
                            ("video", "Video"),
                            ("localization", "Localization"),
                            ("theme", "Theme"),
                            ("security", "Security"),
                        ],
                        db_index=True,
                        help_text="Unique code for the category",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Display name for the category", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this category contains"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for the category (e.g., 'settings', 'match')",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Order for displaying categories"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether this category is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting Category",
                "verbose_name_plural": "Setting Categories",
                "db_table": "settings_categories",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="SettingDefinition",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the setting (e.g., 'match.auto_score')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Display name for the setting", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this setting does"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("json", "JSON"),
                            ("text", "Text"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("phone", "Phone"),
                            ("color", "Color"),
                            ("select", "Select"),
                            ("multiple_select", "Multiple Select"),
                        ],
                        default="string",
                        help_text="Data type of the setting value",
                        max_length=30,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("organization", "Organization"), ("system", "System")],
                        db_index=True,
                        default="organization",
                        help_text="Scope of the setting (organization or system)",
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Whether this setting is required"
                    ),
                ),
                (
                    "default_value",
                    models.TextField(blank=True, help_text="Default value for the setting"),
                ),
                (
                    "help_text",
                    models.TextField(blank=True, help_text="Help text to display for this setting"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Order for displaying settings"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this setting definition is active",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True, default=dict, help_text="Validation rules for the setting value"
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True, default=list, help_text="Available choices for select types"
                    ),
                ),
                (
                    "depends_on",
                    models.CharField(
                        blank=True, help_text="Code of the setting this depends on", max_length=100
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this setting belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to="settings.settingcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting Definition",
                "verbose_name_plural": "Setting Definitions",
                "db_table": "settings_definitions",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the theme",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Display name for the theme", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this theme"),
                ),
                (
                    "theme_type",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("custom", "Custom")],
                        default="light",
                        help_text="Type of theme",
                        max_length=20,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6", help_text="Primary color (hex)", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#10B981", help_text="Secondary color (hex)", max_length=7
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#F59E0B", help_text="Accent color (hex)", max_length=7
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#F9FAFB", help_text="Background color (hex)", max_length=7
                    ),
                ),
                (
                    "surface_color",
                    models.CharField(
                        default="#FFFFFF", help_text="Surface color (hex)", max_length=7
                    ),
                ),
                (
                    "text_primary",
                    models.CharField(
                        default="#111827", help_text="Primary text color (hex)", max_length=7
                    ),
                ),
                (
                    "text_secondary",
                    models.CharField(
                        default="#6B7280", help_text="Secondary text color (hex)", max_length=7
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#E5E7EB", help_text="Border color (hex)", max_length=7
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[("sans", "Sans Serif"), ("serif", "Serif"), ("mono", "Monospace")],
                        default="sans",
                        help_text="Font family",
                        max_length=20,
                    ),
                ),
                (
                    "font_size",
                    models.PositiveSmallIntegerField(default=14, help_text="Base font size (px)"),
                ),
                (
                    "border_radius",
                    models.PositiveSmallIntegerField(default=8, help_text="Border radius (px)"),
                ),
                (
                    "spacing_unit",
                    models.PositiveSmallIntegerField(default=8, help_text="Spacing unit (px)"),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(
                        default=False, help_text="Whether sidebar is collapsed by default"
                    ),
                ),
                (
                    "navbar_fixed",
                    models.BooleanField(default=True, help_text="Whether navbar is fixed at top"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether this theme is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this theme belongs to (null = default theme)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "db_table": "themes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the feature flag",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Display name for the feature flag", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this feature does"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean"),
                            ("percentage", "Percentage"),
                            ("scheduled", "Scheduled"),
                            ("rollout", "Rollout"),
                        ],
                        default="boolean",
                        help_text="Type of feature flag",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("scheduled", "Scheduled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="disabled",
                        help_text="Current status of the feature flag",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, help_text="Whether the feature is enabled"),
                ),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Percentage of users to enable this feature for"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="When to enable this feature", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="When to disable this feature", null=True
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration for the feature flag",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this feature flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization to enable this feature for (null = system-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this feature flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "db_table": "feature_flags",
                "ordering": ("name",),
                "unique_together": {("code", "organization")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationSetting",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="The setting value (stored as JSON string)"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this setting is locked (cannot be changed)",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, help_text="When this setting was locked", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who locked this setting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_organization_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        help_text="The setting definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_values",
                        to="settings.settingdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Setting",
                "verbose_name_plural": "Organization Settings",
                "db_table": "organization_settings",
                "ordering": ("setting__name",),
                "unique_together": {("setting", "organization")},
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="The setting value (stored as JSON string)"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this setting is locked (cannot be changed)",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, help_text="When this setting was locked", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who locked this setting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_system_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        help_text="The setting definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_values",
                        to="settings.settingdefinition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
                "ordering": ("setting__name",),
                "unique_together": {("setting",)},
            },
        ),
    ]
