# Generated by Django 6.0.6 on 2026-08-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localization",
            name="status",
        ),
        migrations.RemoveField(
            model_name="organizationsetting",
            name="status",
        ),
        migrations.RemoveField(
            model_name="settingcategory",
            name="status",
        ),
        migrations.RemoveField(
            model_name="settingdefinition",
            name="status",
        ),
        migrations.RemoveField(
            model_name="systemsetting",
            name="status",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="status",
        ),
    ]
