# Generated by Django 6.0.6 on 2026-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_remove_localization_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingcategory",
            name="code",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("project", "Project"),
                    ("media", "Media"),
                    ("workflow", "Workflow"),
                    ("review", "Review"),
                    ("delivery", "Delivery"),
                    ("notification", "Notification"),
                    ("billing", "Billing"),
                    ("branding", "Branding"),
                    ("analytics", "Analytics"),
                    ("ai", "AI"),
                    ("localization", "Localization"),
                    ("theme", "Theme"),
                    ("security", "Security"),
                ],
                db_index=True,
                help_text="Unique code for the category",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="settingcategory",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon name for the category (e.g., 'settings', 'project')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="settingdefinition",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique code for the setting (e.g., 'project.default_fps')",
                max_length=100,
                unique=True,
            ),
        ),
    ]
