from django.db import models


class SecurityEventType(models.TextChoices):
    LOGIN_SUCCESS = "login_success", "Login Success"
    LOGIN_FAILED = "login_failed", "Login Failed"
    LOGIN_LOCKED = "login_locked", "Login Locked"
    PASSWORD_CHANGED = "password_changed", "Password Changed"
    PASSWORD_RESET = "password_reset", "Password Reset"
    EMAIL_VERIFIED = "email_verified", "Email Verified"
    MFA_ENABLED = "mfa_enabled", "MFA Enabled"
    MFA_DISABLED = "mfa_disabled", "MFA Disabled"
    MFA_VERIFIED = "mfa_verified", "MFA Verified"
    TOKEN_REFRESHED = "token_refreshed", "Token Refreshed"
    SESSION_CREATED = "session_created", "Session Created"
    SESSION_TERMINATED = "session_terminated", "Session Terminated"
    ACCOUNT_LOCKED = "account_locked", "Account Locked"
    ACCOUNT_UNLOCKED = "account_unlocked", "Account Unlocked"
    IP_BLOCKED = "ip_blocked", "IP Blocked"
    IP_UNBLOCKED = "ip_unblocked", "IP Unblocked"
    TRUSTED_DEVICE_ADDED = "trusted_device_added", "Trusted Device Added"
    TRUSTED_DEVICE_REMOVED = "trusted_device_removed", "Trusted Device Removed"
    PROFILE_UPDATED = "profile_updated", "Profile Updated"
    SETTINGS_UPDATED = "settings_updated", "Settings Updated"
    API_KEY_CREATED = "api_key_created", "API Key Created"
    API_KEY_REVOKED = "api_key_revoked", "API Key Revoked"
    PERMISSION_CHANGED = "permission_changed", "Permission Changed"
    ROLE_CHANGED = "role_changed", "Role Changed"
    USER_CREATED = "user_created", "User Created"
    USER_DELETED = "user_deleted", "User Deleted"
    SUSPICIOUS_ACTIVITY = "suspicious_activity", "Suspicious Activity"
    DATA_EXPORT = "data_export", "Data Export"
    DATA_IMPORT = "data_import", "Data Import"


class OAuthProviderName(models.TextChoices):
    GOOGLE = "google", "Google"
    GITHUB = "github", "GitHub"
    GITLAB = "gitlab", "GitLab"
    BITBUCKET = "bitbucket", "Bitbucket"
    FACEBOOK = "facebook", "Facebook"
    LINKEDIN = "linkedin", "LinkedIn"
    TWITTER = "twitter", "Twitter"
    MICROSOFT = "microsoft", "Microsoft"
    APPLE = "apple", "Apple"
    SLACK = "slack", "Slack"
    DISCORD = "discord", "Discord"
    AUTH0 = "auth0", "Auth0"
    OKTA = "okta", "Okta"
    CUSTOM = "custom", "Custom"
