# Generated by Django 6.0.6 on 2026-08-07 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_ipblacklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("password_changed", "Password Changed"),
                            ("email_verification", "Email Verification"),
                            ("mfa_verification", "MFA Verification"),
                            ("login_alert", "Login Alert"),
                            ("security_alert", "Security Alert"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("password_reset", "Password Reset"),
                            ("invitation", "Invitation"),
                            ("team_update", "Team Update"),
                            ("project_update", "Project Update"),
                            ("task_assigned", "Task Assigned"),
                            ("task_completed", "Task Completed"),
                            ("reminder", "Reminder"),
                            ("billing", "Billing"),
                            ("subscription", "Subscription"),
                            ("payment", "Payment"),
                            ("system", "System"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                            ("webhook", "Webhook"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_notification_templates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("password_changed", "Password Changed"),
                            ("email_verification", "Email Verification"),
                            ("mfa_verification", "MFA Verification"),
                            ("login_alert", "Login Alert"),
                            ("security_alert", "Security Alert"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("password_reset", "Password Reset"),
                            ("invitation", "Invitation"),
                            ("team_update", "Team Update"),
                            ("project_update", "Project Update"),
                            ("task_assigned", "Task Assigned"),
                            ("task_completed", "Task Completed"),
                            ("reminder", "Reminder"),
                            ("billing", "Billing"),
                            ("subscription", "Subscription"),
                            ("payment", "Payment"),
                            ("system", "System"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                            ("webhook", "Webhook"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="identity.notificationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "identity_notifications",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OAuthProvider",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("microsoft", "Microsoft"),
                            ("apple", "Apple"),
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                            ("auth0", "Auth0"),
                            ("okta", "Okta"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("authorization_url", models.URLField()),
                ("token_url", models.URLField()),
                ("userinfo_url", models.URLField(blank=True)),
                ("scope", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_oauth_providers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_account_id", models.CharField(db_index=True, max_length=255)),
                ("access_token", models.CharField(blank=True, max_length=1024)),
                ("refresh_token", models.CharField(blank=True, max_length=1024)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_connected", models.BooleanField(db_index=True, default=True)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to="identity.oauthprovider",
                    ),
                ),
            ],
            options={
                "db_table": "identity_oauth_accounts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("login_locked", "Login Locked"),
                            ("password_changed", "Password Changed"),
                            ("password_reset", "Password Reset"),
                            ("email_verified", "Email Verified"),
                            ("mfa_enabled", "MFA Enabled"),
                            ("mfa_disabled", "MFA Disabled"),
                            ("mfa_verified", "MFA Verified"),
                            ("token_refreshed", "Token Refreshed"),
                            ("session_created", "Session Created"),
                            ("session_terminated", "Session Terminated"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("ip_blocked", "IP Blocked"),
                            ("ip_unblocked", "IP Unblocked"),
                            ("trusted_device_added", "Trusted Device Added"),
                            ("trusted_device_removed", "Trusted Device Removed"),
                            ("profile_updated", "Profile Updated"),
                            ("settings_updated", "Settings Updated"),
                            ("api_key_created", "API Key Created"),
                            ("api_key_revoked", "API Key Revoked"),
                            ("permission_changed", "Permission Changed"),
                            ("role_changed", "Role Changed"),
                            ("user_created", "User Created"),
                            ("user_deleted", "User Deleted"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("data_export", "Data Export"),
                            ("data_import", "Data Import"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_critical", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_security_events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="KnownDevice",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Object creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Last update timestamp."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=255)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("is_trusted", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who deleted this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who last updated this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "identity_known_devices",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["user"], name="identity_kn_user_id_fa09c3_idx"),
                    models.Index(fields=["fingerprint"], name="identity_kn_fingerp_70039f_idx"),
                    models.Index(fields=["is_trusted"], name="identity_kn_is_trus_7cf26b_idx"),
                ],
                "unique_together": {("user", "fingerprint")},
            },
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(fields=["template_type"], name="identity_no_templat_57aaa8_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(fields=["channel"], name="identity_no_channel_86847b_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(fields=["is_active"], name="identity_no_is_acti_673067_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "status"], name="identity_no_user_id_e8f8f6_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["notification_type"], name="identity_no_notific_bf448e_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["channel"], name="identity_no_channel_ae4248_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["sent_at"], name="identity_no_sent_at_2bdc3d_idx"),
        ),
        migrations.AddIndex(
            model_name="oauthaccount",
            index=models.Index(fields=["user"], name="identity_oa_user_id_139cfb_idx"),
        ),
        migrations.AddIndex(
            model_name="oauthaccount",
            index=models.Index(fields=["provider"], name="identity_oa_provide_11fa65_idx"),
        ),
        migrations.AddIndex(
            model_name="oauthaccount",
            index=models.Index(fields=["is_connected"], name="identity_oa_is_conn_c33f01_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="oauthaccount",
            unique_together={("provider", "provider_account_id")},
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["event_type"], name="identity_se_event_t_2615be_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["is_critical"], name="identity_se_is_crit_87a3af_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["created_at"], name="identity_se_created_488844_idx"),
        ),
    ]
