# Generated by Django 6.0.6 on 2026-08-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_loginhistory_usersession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backupcode",
            name="status",
        ),
        migrations.RemoveField(
            model_name="ipblacklist",
            name="status",
        ),
        migrations.RemoveField(
            model_name="knowndevice",
            name="status",
        ),
        migrations.RemoveField(
            model_name="loginattempt",
            name="status",
        ),
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="status",
        ),
        migrations.RemoveField(
            model_name="oauthaccount",
            name="status",
        ),
        migrations.RemoveField(
            model_name="oauthprovider",
            name="status",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="status",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="status",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]
