# Generated by Django 6.0.6 on 2026-08-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_remove_usersession_loginhistory_rename_loginattempt_success"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="backupcode",
            constraint=models.UniqueConstraint(
                fields=("user", "code_hash"), name="uniq_backup_code_user_hash"
            ),
        ),
    ]
