# Generated by Django 6.0.6 on 2026-08-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0007_backupcode_uniq_backup_code_user_hash"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="identity_no_user_id_e8f8f6_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="identity_no_notific_bf448e_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="identity_no_channel_ae4248_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="identity_no_sent_at_2bdc3d_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationtemplate",
            name="identity_no_templat_57aaa8_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationtemplate",
            name="identity_no_channel_86847b_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationtemplate",
            name="identity_no_is_acti_673067_idx",
        ),
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationTemplate",
        ),
    ]
