# Generated by Django 6.0.6 on 2026-09-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0008_remove_notification_identity_no_user_id_e8f8f6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="must_change_password",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
