# Generated by Django 6.0.6 on 2026-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0009_profile_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
